# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy/product/product_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dummy/product/product_service.proto", :syntax => :proto3) do
    add_message "dummy.product.ShowRequest" do
      optional :id, :string, 1
    end
    add_message "dummy.product.ProductResponse" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :price, :int32, 3
    end
  end
end

module Dummy
  module Product
    ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy.product.ShowRequest").msgclass
    ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy.product.ProductResponse").msgclass
  end
end
