# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'product_service_pb.rb'

module Dummy
  module Product
    class ProductService < Twirp::Service
      package 'dummy.product'
      service 'Product'
      rpc :Show, ShowRequest, ProductResponse, :ruby_method => :show
    end

    class ProductClient < Twirp::Client
      client_for ProductService
    end
  end
end
