# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy/product/product_service.proto

require 'google/protobuf'


descriptor_data = "\n#dummy/product/product_service.proto\x12\rdummy.product\"\x19\n\x0bShowRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x32M\n\x07Product\x12\x42\n\x04Show\x12\x1a.dummy.product.ShowRequest\x1a\x1e.dummy.product.ProductResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Dummy
  module Product
    ShowRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy.product.ShowRequest").msgclass
    ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy.product.ProductResponse").msgclass
  end
end
